import anthropic
import os

def generate_readme():
    try:
        # Configure the Anthropic API client
        client = anthropic.Anthropic(api_key=os.environ["ANTHROPIC_API_KEY"])

        # Read the existing README.md content
        with open("/home/ubuntu/FashionMuseRN/README.md", "r") as f:
            readme_content = f.read()

        # Create the prompt for Anthropic
        prompt = """
As an expert technical writer, your task is to refine and enhance the following README.md for the Fashion Muse Studio React Native app. Your goal is to make it more comprehensive, professional, and appealing to developers, while maintaining the existing structure.

**Key areas to improve:**

1.  **Introduction:** Rewrite the introduction to be more engaging and highlight the app's value proposition.
2.  **Features:** Expand the feature list with more detail and group related features under subheadings.
3.  **Design System:** Elaborate on the design system, explaining the rationale behind the color choices and the implementation of glassmorphism.
4.  **Future Enhancements:** Brainstorm and add more creative and valuable ideas to the "TODO & Future Enhancements" section.
5.  **Tone and Style:** Ensure the entire document has a professional, polished, and consistent tone.

**Existing README.md content:**

""" + readme_content + """

**Your refined and enhanced README.md:**
"""

        # Generate the enhanced content
        message = client.messages.create(
            model="claude-3-opus-20240229",
            max_tokens=4000,
            messages=[
                {
                    "role": "user",
                    "content": prompt
                }
            ]
        )

        # Save the enhanced content to a new file
        with open("/home/ubuntu/FashionMuseRN/README_Anthropic.md", "w") as f:
            f.write(message.content[0].text)

        print("Enhanced README.md generated by Anthropic and saved to /home/ubuntu/FashionMuseRN/README_Anthropic.md")

    except Exception as e:
        print(f"An error occurred during Anthropic generation: {e}")

if __name__ == "__main__":
    generate_readme()

